-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_quotation_requests" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "title" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "assignStatus" TEXT,
    "opportunityId" TEXT,
    "accountName" TEXT,
    "endUserName" TEXT,
    "quotationNumber" TEXT,
    "salesBranch" TEXT,
    "installLocation" TEXT,
    "installEnvironment" TEXT,
    "submissionDeadline" DATETIME,
    "salesPersonId" TEXT,
    "sePersonId" TEXT,
    "seGroupLeaderId" TEXT,
    "seManagerId" TEXT,
    "seDepartment" TEXT,
    "seManagerComment" TEXT,
    "seNote" TEXT,
    "seWorkStartDate" DATETIME,
    "seWorkEndDate" DATETIME,
    "seWorkEndActual" DATETIME,
    "assignDate" DATETIME,
    "ownerId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "salesOffice" TEXT,
    "salesPersonName" TEXT,
    "endUserName2" TEXT,
    "installEnvType" TEXT,
    "tempSpecial" BOOLEAN NOT NULL DEFAULT false,
    "cleanRoom" BOOLEAN NOT NULL DEFAULT false,
    "hazardStorage" BOOLEAN NOT NULL DEFAULT false,
    "envOther" BOOLEAN NOT NULL DEFAULT false,
    "tempSpecialDetail" TEXT,
    "cleanRoomDetail" TEXT,
    "hazardStorageDetail" TEXT,
    "envOtherDetail" TEXT,
    "loadType" TEXT,
    "loadSize" TEXT,
    "loadWeight" TEXT,
    "packageCategory" TEXT,
    "palletSize" TEXT,
    "procurementType" TEXT,
    "buildingType" TEXT,
    "installSpace" TEXT,
    "architectDrawing" TEXT,
    "exteriorDrawing" TEXT,
    "storageRequirement" TEXT,
    "constructionDoc" TEXT,
    "relatedFilePath" TEXT,
    "reqLayout" BOOLEAN NOT NULL DEFAULT false,
    "reqLoadDetail" BOOLEAN NOT NULL DEFAULT false,
    "reqCapacity" BOOLEAN NOT NULL DEFAULT false,
    "reqOperation" BOOLEAN NOT NULL DEFAULT false,
    "reqOtherDoc" BOOLEAN NOT NULL DEFAULT false,
    "submitLayout" BOOLEAN NOT NULL DEFAULT false,
    "submitCostSheet" BOOLEAN NOT NULL DEFAULT false,
    "submitAxialForce" BOOLEAN NOT NULL DEFAULT false,
    "submitPowerReq" BOOLEAN NOT NULL DEFAULT false,
    "submitSpecSheet" BOOLEAN NOT NULL DEFAULT false,
    "submitOther" BOOLEAN NOT NULL DEFAULT false,
    "desiredDeadline" DATETIME,
    "salesComment" TEXT,
    "managerComment" TEXT,
    "sourceQuotationId" TEXT,
    CONSTRAINT "quotation_requests_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "quotation_requests_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "opportunities" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "quotation_requests_salesPersonId_fkey" FOREIGN KEY ("salesPersonId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "quotation_requests_sePersonId_fkey" FOREIGN KEY ("sePersonId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "quotation_requests_seGroupLeaderId_fkey" FOREIGN KEY ("seGroupLeaderId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "quotation_requests_seManagerId_fkey" FOREIGN KEY ("seManagerId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_quotation_requests" ("accountName", "assignDate", "assignStatus", "createdAt", "endUserName", "id", "installEnvironment", "installLocation", "name", "opportunityId", "ownerId", "quotationNumber", "salesBranch", "salesPersonId", "seDepartment", "seGroupLeaderId", "seManagerComment", "seManagerId", "seNote", "sePersonId", "seWorkEndActual", "seWorkEndDate", "seWorkStartDate", "status", "submissionDeadline", "title", "updatedAt") SELECT "accountName", "assignDate", "assignStatus", "createdAt", "endUserName", "id", "installEnvironment", "installLocation", "name", "opportunityId", "ownerId", "quotationNumber", "salesBranch", "salesPersonId", "seDepartment", "seGroupLeaderId", "seManagerComment", "seManagerId", "seNote", "sePersonId", "seWorkEndActual", "seWorkEndDate", "seWorkStartDate", "status", "submissionDeadline", "title", "updatedAt" FROM "quotation_requests";
DROP TABLE "quotation_requests";
ALTER TABLE "new_quotation_requests" RENAME TO "quotation_requests";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
